### ISSUE TITLE
Getting a grey screen instead of a map

### ISSUE THREAD

**Issue by maelle** [lmullen/geochecker#1]
I get an error that is maybe hard to reproduce.

If I type

``` r
library("geochecker")
library("opencage")
library("dplyr")
to_check <- opencage_forward(placename = "London")$results
to_check <- rename(to_check, latitude = geometry.lat,
                   longitude = geometry.lng)
corrected <- geocheck(to_check, zoom = 5)
```

I get a gray screen instead of the map in the viewer. The buttons are there, but somehow the gadget doesn't work well. I am attaching a picture and 
![data](https://cloud.githubusercontent.com/assets/8360597/17168127/f0ce5e52-53e0-11e6-8926-01aae837be29.png)
the file I got using `readr::write_csv(to_check, path = "to_check.txt")`
[to_check.txt](https://github.com/lmullen/geochecker/files/385565/to_check.txt)

After I got this error and close the gadget with 

``` r
corrected2 <- geocheck(geocoded_cities)
```

then the Viewer screen looks the same, although if I try this command in a clean session, everything looks good.

I have the latest version of the packages described in `Imports`, the latest R and RStudio version.

**Comment by lmullen** [comment]
@masalmon You're an early adopter! I only pushed this package up last night.

The problem was that dplyr/tibble's methods were being used instead of base R's. But only when dplyr was loaded, which explains why it worked in a clean session. More info: https://github.com/lmullen/geochecker/commit/2a4c4da34cc208651de3a1062c1f74eb0a258465

I've pushed a fix. Would you mind reinstalling and trying it again to verify that it works?

From your test data I see that users are going to need an option to display only a limited number of columns in the popup, which I plan to add. #2

**Comment by maelle** [comment]
I've reinstalled and tried and it works! 

Seeing all the columns would be ok with a fixed height rectangle and the possibility to scroll, do you see what I mean? No idea if it's possible.

**Comment by lmullen** [comment]
Yes, I see what you mean about scrolling in the popup. I might look into that later. But for now there is a new option `popup_cols` which lets you specify which columns you want, otherwise you get everything.
